"""Description of changes

Revision ID: 7e9e4d03480f
Revises: efa6147ae7b8
Create Date: 2023-08-03 16:01:50.081341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e9e4d03480f'
down_revision = 'efa6147ae7b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
