"""Initial migration

Revision ID: b4754bd49bea
Revises: 7a6f92bc116c
Create Date: 2023-08-03 15:04:43.516646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4754bd49bea'
down_revision = '7a6f92bc116c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
