"""Initial migration

Revision ID: efa6147ae7b8
Revises: b4754bd49bea
Create Date: 2023-08-03 16:01:30.094353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efa6147ae7b8'
down_revision = 'b4754bd49bea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
